server {
    listen 80;
    server_name 10.0.1.34;  # Replace with your EC2 public IP or domain name

    location / {
        proxy_pass http://localhost:8080;  # Proxy to Docker container
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

